stridex: 200
stridey: 200
windowsizex: 256
windowsizey: 256
resample: false
resamplesizex: 256
resamplesizey: 256
window_bands: 
- 0
- 1
- 2
- 3
classifier: false
needfiles: true
orig_image_shape: true
fileprefix: ""
file_input_dir: "/contents/predictions/images" # doesn't need a trailing slash
model_input_dir: "/contents/predictions/processed/a/" # include a trailing slash!
model_output_dir: "/contents/predictions/processed/b/" # include a trailing slash!
chop_last_row: 1
chop_last_col: 1
